name: Build test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the Dependiencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display softUni user name
      run: echo "yanabg"

  ui-test:
    runs-on: ubuntu-latest
    needs: build-unit-test
    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the Dependiencies
      run: npm install
    - name: install playwright browsers
      run: npx playwright install
    - name: start teh application
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: ui-test
    steps:
      - name: Deploy
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true


